services:
  backend:
    build: ./app/
    container_name: weather-api
    command: ["python", "main.py"]
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@db:27017/${MONGODB_DATABASE}
    ports:
      - "5000:5000"  # Пример порта для API

  db:
    image: mongo
    container_name: mongodb_weather
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=weather
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local
